/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Huuxloc (https://sketchfab.com/rjh41)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/backrooms-1da6a7f2e0294ba9a4123f61244811a8
title: BackRooms
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import Backroom from './Models/Backroom.glb';
import { useConvexPolyhedron } from "@react-three/cannon";


export default function BackroomMap({ ...props }) {
  //const group = useRef()
  const { nodes, materials } = useGLTF(Backroom)
  const [ref] = useConvexPolyhedron(() => ({ mass: 100, ...props, type:'Static', 
  position: [18,0,-7], rotation: [0,-0.14,0]
}));
  return (
    <group ref={ref} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.67}>
        <group rotation={[Math.PI / 2, 0, 0]}>
        {/*  <mesh geometry={nodes.Object_4.geometry} material={materials.Carpet} /> */}
          <group position={[-7.3, 0.51, -7.65]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_6.geometry} material={materials.Skirting} />
            <mesh geometry={nodes.Object_7.geometry} material={materials.Wall} />
          </group>
          <group position={[2.64, 0.51, 6.25]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_12.geometry} material={materials.Skirting} />
            <mesh geometry={nodes.Object_13.geometry} material={materials.Wall} />
          </group>
          <group position={[-2.97, 0.51, -0.08]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_15.geometry} material={materials.Skirting} />
            <mesh geometry={nodes.Object_16.geometry} material={materials.Wall} />
          </group>
          <group position={[-7.45, 0.51, -0.02]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_18.geometry} material={materials.Skirting} />
            <mesh geometry={nodes.Object_19.geometry} material={materials.Wall} />
          </group>
          <group position={[-7.3, 0.51, 8.56]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_21.geometry} material={materials.Skirting} />
            <mesh geometry={nodes.Object_22.geometry} material={materials.Wall} />
          </group>
          <group position={[7.97, 0.51, -7.15]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_24.geometry} material={materials.Skirting} />
            <mesh geometry={nodes.Object_25.geometry} material={materials.Wall} />
          </group>
          <group position={[-8.42, 0.51, -7.15]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_27.geometry} material={materials.Skirting} />
            <mesh geometry={nodes.Object_28.geometry} material={materials.Wall} />
          </group>
          <group position={[-6.55, 0.51, -4.87]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_30.geometry} material={materials.Skirting} />
            <mesh geometry={nodes.Object_31.geometry} material={materials.Wall} />
          </group>
          <group position={[5.31, 0.51, -0.16]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Object_33.geometry} material={materials.Skirting} />
            <mesh geometry={nodes.Object_34.geometry} material={materials.Wall} />
          </group>
          <group position={[-2.96, 0.51, -1.81]} rotation={[0, Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_36.geometry} material={materials.Skirting} />
            <mesh geometry={nodes.Object_37.geometry} material={materials.Wall} />
          </group>
          <group position={[-0.59, 0.51, -0.95]}>
            <mesh geometry={nodes.Object_39.geometry} material={materials.Skirting} />
            <mesh geometry={nodes.Object_40.geometry} material={materials.Wall} />
          </group>
          <group position={[-5.33, 0.51, -0.96]}>
            <mesh geometry={nodes.Object_42.geometry} material={materials.Skirting} />
            <mesh geometry={nodes.Object_43.geometry} material={materials.Wall} />
          </group>
          <group position={[-6.1, 0.51, 4.14]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_45.geometry} material={materials.Skirting} />
            <mesh geometry={nodes.Object_46.geometry} material={materials.Wall} />
          </group>
          <group position={[-4.45, 0.51, 1.91]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh geometry={nodes.Object_48.geometry} material={materials.Skirting} />
            <mesh geometry={nodes.Object_49.geometry} material={materials.Wall} />
          </group>
          <group position={[0, 1.92, 0.42]}>
        {/*    <mesh geometry={nodes.Object_51.geometry} material={materials.CeilingFrame} />  */}
          </group>
          <group position={[-0.01, 1.94, 0.46]}>
        {/*    <mesh geometry={nodes.Object_53.geometry} material={materials.Tiles} /> */}
        {/*    <mesh geometry={nodes.Object_54.geometry} material={materials.Light} /> */}
          </group>
          <group position={[-5.9, 0.98, -3.32]}>
            <mesh geometry={nodes.Object_56.geometry} material={materials.Wall} />
            <mesh geometry={nodes.Object_57.geometry} material={materials.Skirting} />
          </group>
          <group position={[-5.9, 0.98, 6.13]}>
            <mesh geometry={nodes.Object_59.geometry} material={materials.Wall} />
            <mesh geometry={nodes.Object_60.geometry} material={materials.Skirting} />
          </group>
          <group position={[-0.04, 0.98, 6.13]}>
            <mesh geometry={nodes.Object_62.geometry} material={materials.Wall} />
            <mesh geometry={nodes.Object_63.geometry} material={materials.Skirting} />
          </group>
          <group position={[5.88, 0.98, 7.07]}>
            <mesh geometry={nodes.Object_65.geometry} material={materials.Wall} />
            <mesh geometry={nodes.Object_66.geometry} material={materials.Skirting} />
          </group>
          <group position={[0.95, 0.98, -3.34]}>
            <mesh geometry={nodes.Object_68.geometry} material={materials.Wall} />
            <mesh geometry={nodes.Object_69.geometry} material={materials.Skirting} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(Backroom)
